In [5]:
import numpy as np
from libeq.data_structure import SolverData
from libeq import EqSolver
from libeq.solver import species_concentration, fobj, damping
import numpy as np

# Create SolverData object
solver_data = SolverData.load_from_bstac(
    "/Users/lorenzo/Coding/libeq/notebooks/Zn-EDTA"
)

In [6]:
stoichiometry = solver_data.stoichiometry
c = solver_data.c0
log_beta = solver_data.log_beta
solid_stoichiometry = solver_data.solid_stoichiometry
full_stoichiometry = np.concatenate((np.eye(solver_data.nc), stoichiometry), axis=1)
c = np.repeat(c[np.newaxis, :], 89, axis=0)
c.shape

(89, 3)

In [8]:
c1 = c
c2 = species_concentration(c, log_beta, stoichiometry, solid_stoichiometry)

c1 + np.sum(c2[:,np.newaxis,:]*stoichiometry[np.newaxis, ...],axis=2) - c

array([[4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372840e+12, 1.57122621e+13],
       [4.42533526e+12, 7.17372

In [3]:
(species_concentration(c, log_beta, stoichiometry, solid_stoichiometry, full=True)[:,np.newaxis,:] * full_stoichiometry).sum(axis=2)

ValueError: operands could not be broadcast together with shapes (89,3) (3,16) 

In [65]:
# Your 2D array
arr = np.arange(32).reshape(2, 16)

# Create a diagonal matrix from the rows of the array using broadcasting
diag_matrices = np.einsum('ij,jk->ijk', arr, np.eye(arr.shape[1]))

In [61]:
F = np.array([[1, 2, 3], [4, 5, 6]])

In [62]:
J = stoichiometry @ diag_matrices @ stoichiometry.T

diagonal_indices = np.diag_indices(J.shape[1])
J[:,diagonal_indices[0], diagonal_indices[1]] += arr[:, :3]
J


array([[[  96.,   42., -113.],
        [  42.,  100.,  216.],
        [-113.,  216., 1339.]],

       [[ 352.,   90., -497.],
        [  90.,  260.,  552.],
        [-497.,  552., 3931.]]])

In [64]:
dx = np.linalg.solve(J, -F)

array([[ 0.00481414, -0.02771813,  0.00263713],
       [-0.00749229, -0.01622185, -0.00019568]])