In [1]:
from libeq.data_structure import SolverData
from libeq.optimizers import PotentiometryOptimizer
import numpy as np

# Create SolverData object
h6l_data = SolverData.load_from_bstac("/Users/lorenzo/Downloads/qb64pe/H6L")
# h6l_data.potentiometry_options.px_range = [1.7,0]

In [2]:
print(h6l_data.potentiometry_opts.weights)
print(h6l_data.potentiometry_opts.px_range)
for t in h6l_data.potentiometry_opts.titrations:
    print(t.electro_active_compoment)
    print(t.slope)
    print(t.e0_sigma, t.v0_sigma)
    # t.slope=(25 + 273.15) / 11.6048 * 2.303

calculated
[0.0, 0.0]
1
59.16857248724665
0.15 0.005
1
59.16857248724665
0.15 0.005
1
59.16857248724665
0.15 0.005
1
59.16857248724665
0.15 0.005
1
59.16857248724665
0.15 0.005
1
59.16857248724665
0.15 0.005


In [3]:
constants, concentrations, b_error, cor_matrix, cov_matrix, return_extra = (
    PotentiometryOptimizer(h6l_data)
)

In [4]:
print("Constants:")
for b, e in zip(constants, b_error):
    print(b, e)
print("-" * 20)

print("Concentrations:")
print(concentrations)
print("-" * 20)


print("Correlation matrix:")
print(cor_matrix)
print("-" * 20)

Constants:
10.009949268841277 0.0032915045872157237
18.013508815748896 0.004592013813940182
24.01647574853225 0.005588411929865904
28.01884725126332 0.006510533120991051
31.01983378459971 0.006752431177731802
33.0256790305685 0.010041961686094789
--------------------
Concentrations:
[[1.75803873e-22 4.38439193e-03 3.87338468e-12 ... 6.78442690e-04
  2.98132327e-03 1.32484077e-03]
 [2.63820325e-22 4.04562301e-03 4.19773086e-12 ... 7.38069304e-04
  2.99274068e-03 1.22715591e-03]
 [4.02499675e-22 3.71896031e-03 4.56644737e-12 ... 8.04079447e-04
  2.99714006e-03 1.12972783e-03]
 ...
 [2.91455491e-03 2.21509601e-12 7.66668191e-03 ... 7.32807177e-22
  1.62692976e-30 3.65263776e-40]
 [2.90285943e-03 2.08231434e-12 8.15555853e-03 ... 5.69978430e-22
  1.18957340e-30 2.51063039e-40]
 [2.88471872e-03 1.91243697e-12 8.87999805e-03 ... 4.02994614e-22
  7.72454494e-31 1.49728778e-40]]
--------------------
Correlation matrix:
[[1.         0.6163679  0.51708922 0.44251069 0.42761103 0.28666258]
 [0.61

In [7]:
return_extra["read_potential"]

[array([ 265.6,  263.5,  261.4,  259.1,  256.7,  254.2,  251.6,  248.8,
         245.9,  242.9,  239.7,  236.3,  232.8,  229.1,  225.2,  221.1,
         216.9,  212.4,  207.8,  203. ,  197.9,  192.7,  187.2,  181.5,
         175.5,  169.2,  162.4,  155. ,  146.7,  137.1,  125.6,  112.2,
          98. ,   84.9,   73.6,   63.6,   54.2,   45.1,   35.7,   25.5,
          14. ,    0.6,  -14. ,  -27.9,  -40.1,  -50.6,  -60.2,  -69.4,
         -78.6,  -88.4,  -99.2, -111.6, -125.6, -139.7, -152.3, -163. ,
        -172.5, -181.1, -189.3, -197.2, -205.1, -212.9, -220.4, -227.5,
        -234. , -239.7, -244.8, -249.2, -253. , -256.5, -259.5, -262.3,
        -264.8, -267.1, -269.1, -271. , -272.9, -274.5, -276. , -277.5,
        -280.2, -283.7, -285.8, -287.6, -289.4, -290.2, -292.5, -294.6,
        -296.5]),
 array([ 265.2,  263.2,  261. ,  258.7,  256.3,  253.8,  251.2,  248.4,
         245.5,  242.5,  239.3,  235.9,  232.4,  228.6,  224.8,  220.7,
         216.4,  212. ,  207.4,  202.5,  197.5

In [5]:
return_extra["calculated_potential"]

[array([ 265.50028032,  263.43425177,  261.27120975,  259.00420323,
         256.62598179,  254.129081  ,  251.50593489,  248.74901065,
         245.85095361,  242.80472192,  239.60368401,  236.24165089,
         232.71282592,  229.01167949,  225.13279228,  221.07074784,
         216.82017033,  212.37596827,  207.73373014,  202.89001246,
         197.84200579,  192.58588132,  187.11317038,  181.40484687,
         175.42309367,  169.10052931,  162.32557539,  154.92079385,
         146.61000362,  136.97967163,  125.51380819,  112.05549253,
          97.8433178 ,   84.79985547,   73.46895595,   63.40711778,
          54.04712057,   44.89411023,   35.48465547,   25.310728  ,
          13.77765165,    0.41698778,  -14.19605951,  -28.12524018,
         -40.23979018,  -50.79712596,  -60.39996502,  -69.58533298,
         -78.82315247,  -88.59027891,  -99.43480457, -111.91095321,
        -125.98744621, -140.15966202, -152.74347276, -163.51755048,
        -172.97492621, -181.60605568, -189.76651

In [6]:
np.sqrt(np.diag(cov_matrix)) / 2.303

array([0.00329091, 0.00459119, 0.00558741, 0.00650936, 0.00675121,
       0.01004015])