In [1]:
from libeq import SolverData, species_concentration, uncertanties, EqSolver
import numpy as np

# Create SolverData object
solver_data = SolverData.load_from_pyes(
    "/Users/lorenzo/Coding/libeq/notebooks/cu_gly_solid.json"
)
solver_data.ionic_strength_dependence = True
result, log_beta, log_ks, saturation_index, total_concentration = EqSolver(
    solver_data, mode="distribution"
)
concentrations = species_concentration(
    result, log_beta, solver_data.stoichiometry, full=True
)

In [2]:
concentrations

array([[9.97955732e-04, 1.40923092e-11, 1.00000000e-02, ...,
        2.04339382e-06, 2.02232087e-10, 1.91739309e-12],
       [9.96941165e-04, 2.06765655e-11, 7.94328235e-03, ...,
        3.05753568e-06, 4.48532967e-10, 2.38995819e-12],
       [9.95483218e-04, 3.00180058e-11, 6.30957344e-03, ...,
        4.51473523e-06, 9.70312122e-10, 2.98211580e-12],
       ...,
       [1.38644914e-15, 1.97681311e-03, 1.58489319e-12, ...,
        4.03793775e-10, 5.64442781e-06, 1.20172749e-02],
       [8.88607131e-16, 1.98369203e-03, 1.25892541e-12, ...,
        2.51978173e-10, 3.48224793e-06, 1.53501041e-02],
       [5.70501524e-16, 1.98840663e-03, 1.00000000e-12, ...,
        1.56851813e-10, 2.13746348e-06, 1.96343107e-02]])

In [3]:
uncertanties(
    concentrations,
    solver_data.stoichiometry,
    solver_data.solid_stoichiometry,
    log_beta,
    log_ks,
    solver_data.log_beta_sigma,
    solver_data.log_ks_sigma,
    np.tile(solver_data.distribution_opts.c0_sigma, (concentrations.shape[0], 1)),
    solver_data.distribution_opts.independent_component,
)

(array([[9.98058111e-06, 7.32645597e-13, 0.00000000e+00, ...,
         1.43029001e-07, 3.14233150e-11, 8.82992150e-14],
        [9.97155827e-06, 1.01182775e-12, 0.00000000e+00, ...,
         2.06947596e-07, 6.78809858e-11, 1.10061642e-13],
        [9.95919088e-06, 1.37102137e-12, 0.00000000e+00, ...,
         2.94636431e-07, 1.42805591e-10, 1.37331508e-13],
        ...,
        [1.59620856e-16, 1.97418527e-05, 0.00000000e+00, ...,
         4.99896719e-11, 9.15602971e-07, 5.53415959e-04],
        [1.02304677e-16, 1.98009732e-05, 0.00000000e+00, ...,
         3.12525535e-11, 5.67297267e-07, 7.06898418e-04],
        [6.56814152e-17, 1.98543718e-05, 0.00000000e+00, ...,
         1.94765881e-11, 3.49147471e-07, 9.04193425e-04]]),
 array([[0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
     